manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: sayu-hub
      url-base: https://github.com/sayu-hub
    - name: kloir-z
      url-base: https://github.com/kloir-z
    - name: caksoylar  # <-- led
      url-base: https://github.com/caksoylar  
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-pmw3610-driver  # <-- トラボドライバ
      remote: sayu-hub
      revision: main
    - name: zmk-rgbled-widget  # <-- led
      remote: caksoylar
      revision: main
  self:
    path: config
